/**
 * Represents an event, combining database fields with frontend-specific formatted fields.
 */
export interface EventType {
  // --- Core Database Fields (Raw ISO Strings from DB) ---
  id: string;                      // UUID, Primary Key
  slug: string;                    // URL-friendly identifier
  event_start: string;             // ADDED: ISO String from DB timestamptz
  event_end: string | null;        // ADDED: ISO String from DB timestamptz (or null)

  // --- Other Database Fields ---
  title: string | null;
  description: string | null;
  location: string | null;
  type: string | null;             // Event category (e.g., 'Ceremony', 'Social')
  price: number | null;
  maxAttendees: number | null;     // Capacity
  featured: boolean | null;        // Featured on homepage/listings
  imageUrl: string | null;         // URL for the event image

  // --- Additional Database Fields ---
  is_multi_day: boolean | null;    // If the event spans multiple days
  parent_event_id: string | null;  // Foreign key to self (for sub-events)
  event_includes: string[] | null;      // List of items included
  important_information: string[] | null; // List of important notes
  latitude: number | null;         // For mapping
  longitude: number | null;        // For mapping
  is_purchasable_individually: boolean | null; // Can this event be bought outside a package?
  created_at: string;              // Timestamp

  // --- Deprecated Raw Fields (Commented Out) ---
  // date?: string | null;          // Use event_start
  // start_time?: string | null;    // Use event_start
  // end_time?: string | null;      // Use event_end
  // end_date?: string | null;      // Use event_end

  // --- Frontend-Specific Formatted Fields (Derived by formatEventForDisplay) ---
  day?: string;                     // e.g., "Sunday, 27 April 25"
  date?: string;                    // e.g., "27-04-2025"
  time?: string;                    // e.g., "06:00 PM"
  until?: string;                   // ADDED: e.g., "09:00 PM"
  imageSrc?: string;                // Optional alias for imageUrl
  
  // --- Potentially Redundant Formatted Fields (Check Usage) ---
  // These might be derivable from event_start/event_end now
  startTimeFormatted?: string;      // e.g., "19:00"
  endTimeFormatted?: string;        // e.g., "21:00"
}

// Note: The database schema also includes 'day' and 'time' fields directly.
// Their purpose needs clarification. If they are pre-formatted strings,
// the frontend formatters might need adjustment or these fields could be used directly.
// The current interface assumes 'day' and 'time' are generated by frontend formatters.

/**
 * Represents the summarized data for a specific day used in the overview section.
 */
export interface EventDayOverviewType {
  id: string;
  date: string; // YYYY-MM-DD  name: string; // Day title/theme
  featured_events_summary?: string | null; // ADDED: Pre-formatted summary string
}