name: Supabase Branch Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'supabase/**'

jobs:
  wait:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outputs.conclusion }}
    steps:
      - uses: fountainhead/action-wait-for-check@v1.2.0
        id: check
        with:
          checkName: Supabase Preview
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          timeoutSeconds: 900

  validate:
    needs:
      - wait
    if: ${{ needs.wait.outputs.status == 'success' }}
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Get preview branch details
        run: supabase --experimental branches get "$GITHUB_HEAD_REF" -o env >> $GITHUB_ENV
        
      - name: Verify migration success
        run: |
          echo "✅ Supabase Preview branch is ready"
          echo "Branch: $GITHUB_HEAD_REF" 